/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2023-02-03 16:12:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.RCS.*;
import java.sql.*;
import java.sql.*;
import java.sql.*;

public final class Approval_005fDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Pages/Page_Function/Header.jsp", Long.valueOf(1675433330000L));
    _jspx_dependants.put("/Pages/Page_Function/Tabs.jsp", Long.valueOf(1675435298000L));
    _jspx_dependants.put("/Pages/Page_Function/Alert.jsp", Long.valueOf(1675433330000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.RCS");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(session.getAttribute("Access_Type") !="2"){
	session.setAttribute("Alert","您無權存取此網頁，或超過存取期限！將自動跳轉登入頁面！");
	response.sendRedirect("../Index.jsp");}


      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../Css/Css_Reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../Css/Header_Footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../Css/User_Style.css\">\r\n");
      out.write("    <title>租借教室 - 國立臺北護理健康大學</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 //公告
    if(session.getAttribute("Alert") != null && (String)session.getAttribute("Alert") != ""){
    	out.print("<script>alert('"+(String) session.getAttribute("Alert")+"');</script>");
    	session.setAttribute("Alert","");
    }

      out.write("\r\n");
      out.write("    ");
 
    String Serial_Number = (String)request.getParameter("Serial_Number");
    DB_CRUD DB = new DB_CRUD();
    ResultSet rs =DB.getResultSet("SELECT * FROM Rental_Record Where Rental_Serial_Number ='" + Serial_Number + "'");
    rs.last();
    
    
    
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("	\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"Header\">\r\n");
      out.write("        <div class=\"Head\">\r\n");
      out.write("            <img src=\"../Images/System_Logo.png\" alt=\"\">\r\n");
      out.write("            <h1>教室租借系統</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"Logout\">\r\n");
      out.write("            <p>歡迎！");
      out.print( session.getAttribute("Access_Name") );
      out.write("</p>\r\n");
      out.write("            <a  href=\"Page_Function/Logout.jsp\">登出</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"Approval Container\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"Tabs\">\r\n");
      out.write("      <li><a href=\"Search_Place.jsp\">場地租借/查詢</a></li>\r\n");
      out.write("      <li><a href=\"Rental_Record.jsp\">租借紀錄</a></li>\r\n");
      out.write("      <li><a href=\"Approval.jsp\">審核專區</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<div class=\"Img\"></div>");
      out.write("\r\n");
      out.write("        <p class=\"Bar\">目前位置：租借審核 / ");
      out.print(Serial_Number );
      out.write("</p>\r\n");
      out.write("       \r\n");
      out.write("      	\r\n");
      out.write("	        <table>\r\n");
      out.write("	                <tr><th>帳號</th><td>");
      out.print(rs.getString(6) );
      out.write("</td></tr>\r\n");
      out.write("	                <tr><th>租借地點</th><td>");
      out.print(rs.getString(2) );
      out.write("</td></tr>\r\n");
      out.write("	                <tr><th>租借日期</th><td>");
      out.print(rs.getDate(4) );
      out.write("</td></tr>\r\n");
      out.write("	                <tr><th>租借時段</th><td>");
      out.print(rs.getString(5) );
      out.write("</td></tr>\r\n");
      out.write("	                <tr><th>租借事由</th><td>");
      out.print(rs.getString(7) );
      out.write("</td></tr>\r\n");
      out.write("	        </table>\r\n");
      out.write("	        <div style=\"display:flex;justify-content:center;margin-top:20px;\";>\r\n");
      out.write("		        <a style=\"margin-right:30px;height:40px;width:80px;text-align:center;font-size:30px;font-weight: bold;text-decoration:none;color:red;\" href=\"Page_Function/Approving.jsp?Serial_Number=");
      out.print(Serial_Number);
      out.write("&Agree=F\">拒絕</a>\r\n");
      out.write("		        <a style=\"height:40px;width:80px;text-align:center;font-size:30px;font-weight: bold;text-decoration:none;color:red;\" href=\"Page_Function/Approving.jsp?Serial_Number=");
      out.print(Serial_Number);
      out.write("&Agree=T\">核准</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Page_Function/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
